### ISSUE TITLE
Number of issues with a certain label not always appearing.

### ISSUE THREAD

**Issue by itsagift** [up-for-grabs/up-for-grabs.net#3417] opened 2022-10-01 01:36 UTC
Here we have a side by side example: 
<img width="754" alt="Screen Shot 2022-09-30 at 9 32 45 PM" src="https://user-images.githubusercontent.com/30632225/193377945-6bca9369-e54d-4dc4-a6a1-358791605ba4.png">

Monument-cli has a 1 next to it, as it should, but Node Efficentnet doesn't have the number of open issues with that label (I checked, there are 8). 

I am a first-time contributor, interested in fixing this myself if it's a real bug.

**Comment by ritwik12** [comment] 2022-10-02 21:54
@itsagift Thanks for opening this, looks like a bug. Maybe the issue is not with the code but the .yml file for this project. Please check that too.

**Comment by SaadOps** [comment] 2022-10-03 09:27
the stats: issue count was missing in yml file
#3441 pr made
also updating other files which I  can find in the same pr

Also @ritwik12 can you please specify what does last-updated means in the yml files , does that mean the time when the project was added to the repo?

**Comment by shiftkey** [comment] 2022-10-08 15:20
> Monument-cli has a 1 next to it, as it should, but Node Efficentnet doesn't have the number of open issues with that label (I checked, there are 8).

There's two ways that we generate this number for a project:

 - [the original way was to make a browser request for the project to the GitHub API](https://github.com/up-for-grabs/up-for-grabs.net/blob/816a1c4e55f992030e05405f800aaf7d1c963861/javascripts/fetchIssueCount.js#L150-L218) and store that in the user's local storage
    - this has several limitations and can be rate-limited because the request is unauthenticated
 - the new way which is to generate the project stats and include them with project metadata (so we don't need to make any API calls)
   - example PR: https://github.com/up-for-grabs/up-for-grabs.net/pull/3463
   - [workflow file](https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/.github/actions/update-stats/update_stats.rb)
   - [logic for checking label](https://github.com/up-for-grabs/tooling/blob/main/lib/queries/github_repository_label_active_check.rb)

The latter approach here should be generated using PRs, and as we talked about in #3441 this file and some others have not been included because they're named `.yaml`. 

We should look at warning users who add `.yaml` files, as we're allowing them here: https://github.com/up-for-grabs/tooling/blob/abd9e70a8adc0e75671a1732eb3eddee84fd0001/lib/validators/pull_request.rb#L32-L39

> Also @ritwik12 can you please specify what does last-updated means in the yml files , does that mean the time when the project was added to the repo?

The `last_updated` value is generated from the issues found with this label - how recently were any of these issues updated? 

```rb
    last_updated = (label.issues.nodes[0].updated_at if count.positive?)
```

Again, this should be related to project activity, not when it was listed in this repository.

Because of the lack of movement on this file renaming I've opened https://github.com/up-for-grabs/up-for-grabs.net/pull/3462 to just get this moving, and then I can re-run the "Update stats" workflow to regenerate the project metadata (this happens daily anyway) which will resolve this.

**Comment by shiftkey** [comment] 2022-10-08 15:45
https://github.com/up-for-grabs/up-for-grabs.net/pull/3464 has been merged and if you look at the devtools you can see the `projects.json` network call (which we use to fetch our project metadata from the server without needing to interact with the GitHub API) has the details populated for `node-efficientnet`:

<img width="818" src="https://user-images.githubusercontent.com/359239/194715831-68a036d0-ed24-4b1a-99ff-80e80f9fb1f3.png">

This is also present on the site when you filter for the project e.g. https://up-for-grabs.net/#/filters?names=619

<img width="1051" src="https://user-images.githubusercontent.com/359239/194715856-4d3e439b-f98d-4731-ab66-fc503bcbab32.png">

Closing this out as resolved - thanks for bringing it to our attention @itsagift and @SaadAnsari17!

**Closed as completed by shiftkey** 2022-10-08 15:45 UTC
