### ISSUE TITLE
JavaScript code formatting

### ISSUE THREAD

**Issue by bigwave** [up-for-grabs/up-for-grabs.net#547] opened 2017-02-04 14:15 UTC
I notice there is an .editorconfig file, I assume that this is for the [EditorConfig for VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) extension and that means that Visual Studio Code is your preferred editor.

However, when I auto-format main.js there are significant changes. 

Should I submit a pull request with auto-reformatted .js files?

**Comment by shiftkey** [comment] 2017-02-05 08:49
[EditorConfig](http://editorconfig.org/) is intended to be tooling-agnostic. It looks like we haven't really defined any JS-specific rules in there, which might explain what you're seeing.

I'd love to see a PR to tidy up the JS files, to ensure we're being consistent. And if there are rules we can specify, let's get them in as well...

**Comment by friendly-developer** [comment] 2017-04-02 15:24
I can help, set up a proper linting tool. For formatting though I use ATOM editor, so I don't know if it's applicable

**Comment by evanplaice** [comment] 2018-01-15 04:42
Why not automate the process?

Requirements:
- Opt to use [standard](https://github.com/standard/standard) or [semistandard](https://github.com/Flet/semistandard) for project-wide style checking
- Add a npm script to run the style checking tool
- Add a [PULL_REQUEST_TEMPLATE.md](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) and add this step to the checklist
- (optional) Add style checking as a pre-commit hook (this may be a bit draconian)

Editorconfig is great for avoiding style issues to begin with but it's easy to fall prey to [sensory adaptation](https://en.wikipedia.org/wiki/Neural_adaptation) while writing code.

**Comment by jacobwardio** [comment] 2018-01-17 21:16
Linting should really only be used for picking up potential errors, rather than enforcing a specific style of coding. Something like [Prettier](https://github.com/prettier/prettier) may be more appropriate.

...my $.02

**Comment by dahlbyk** [comment] 2018-05-07 19:20
Would absolutely welcome JS standards (aligned roughly with how the existing code is written, if possible) configured for Prettier or equivalent. Bonus points for failing the build if formatting is incorrect.

**Comment by jacobwardio** [comment] 2018-05-07 19:35
@dahlbyk I'd like to pick this up, if it's available?

I disagree with failing a build for incorrect formatting. A build should only fail if the code being merged in would break the build.

If the code (regardless of code style) still passes its tests and runs correctly, it won't break the build when integrated, so shouldn't fail it.

I would suggest auto-rejecting any PR with incorrect formatting as a reasonable alternative (as @evanplaice suggested, using a pre-commit hook).

However, I'm happy to implement it whichever way you see fit.

**Comment by ritwik12** [comment] 2018-05-07 19:44
@jacobwarduk Yeah, The build will pass if the code is correct (even if incorrectly formatted). So we are left with auto-rejecting PRs. But I don't think it's a good idea. I will recommend some alternative solution to this apart from these two. It will be good if there's a way to make the build fail on the basis of formatting too. 
Ideas anyone?

**Comment by jacobwardio** [comment] 2018-05-07 20:21
@ritwik12 I think you may have misunderstood what I was saying. 

It is perfectly possible to make the build fail if the code is incorrectly formatted. But you _shouldn't_ fail a build for incorrectly formatted code.

The code works, regardless of formatting. 

Formatting is a stylistic choice, not an error in somebody's code. 

It's still going to work absolutely fine if I mix tabs and spaces or omit the odd semi-colon. 

You _shouldn't_ fail my build if I do that, you _should_ tell me it's not following your style guide, and to change it before trying to commit it.

However, it's up to the maintainer(s) of this project how they want it to behave, and I'm happy to do either.

**Comment by dahlbyk** [comment] 2018-05-07 20:48
> I would suggest auto-rejecting any PR with incorrect formatting

I mean, isn't that what a red build does? Yeah, it's functional, but we hypothetically wouldn't accept a functional-but-poorly-formatted PR anyway. Beyond the ❌ of doom, it's just semantics.

This really seems like a great opportunity to integrate with new [GitHub Checks](https://blog.github.com/2018-05-07-introducing-checks-api/), if you can figure out how to have a linter report warnings through that.
![linter](https://user-images.githubusercontent.com/1319791/39655946-a490fce2-4fca-11e8-88fc-0275bc1f43e7.png)

**Comment by dahlbyk** [comment] 2018-05-07 21:07
Boooo
![The following repositories cannot be migrated to travis-ci.com at this time because they are currently active on our legacy platform travis-ci.org. This feature will be available shortly. Please read our docs on open source migration to learn more.](https://user-images.githubusercontent.com/133987/39725178-981e1182-5210-11e8-89c8-72911ab2c3aa.png)

https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org

**Comment by jacobwardio** [comment] 2018-05-07 21:11
@dahlbyk maybe "rejecting" was a bad choice of word, however I did clarify what I meant by introducing a "pre-commit hook" which won't let you push unless your style is valid.

By doing this, you prevent having a load PRs that are failed builds, and hammering your CI server with builds that you _could know beforehand_ are going to fail.

But like I said, I suppose it's a matter of preference. 

Reporting linting errors/warnings to GitHib checks shouldn't be too much of an issue.

With regards to behaviour, obviously an error would fail. What would the expected behaviour be for warnings?

**Comment by dahlbyk** [comment] 2018-05-07 21:22
@jacobwarduk sorry, I should have clarified: I'm not against using Git hooks to improve the local development experience (good tips [here](http://codeinthehole.com/tips/tips-for-using-a-git-pre-commit-hook/)). But they [aren't automatically set up with the repo](https://stackoverflow.com/questions/3462955/putting-git-hooks-into-repository/3464399#3464399), so we would still want to including a lint step in the build to catch issues that slip through.

> Obvioisly an error would fail. What would the expected behaviour be for warnings?

No idea, honestly. I guess we'll see how GitHub checks works for warnings?

**Comment by jacobwardio** [comment] 2018-05-07 21:55
@dahlbyk okay cool, are you happy for me to pick this up and play it by ear, with regards to GitHub Checks?

**Comment by jacobwardio** [comment] 2018-05-07 21:55
@dahlbyk okay cool, are you happy for me to pick this up and play it by ear, with regards to GitHub Checks?

**Comment by dahlbyk** [comment] 2018-05-08 01:01
Go for it! Sounds like we can convert Travis to support checks as long as we're fine losing old build history, which doesn't seem like it matters for a project like this. Thoughts?

**Comment by ritwik12** [comment] 2018-05-08 07:44
@dahlbyk I agree, I think @jacobwarduk should go for this.

**Comment by jacobwardio** [comment] 2018-05-09 13:59
@dahlbyk @ritwik12 great, got a few hours set aside this evening for coding, so will make a start on it later.

**Comment by shiftkey** [comment] 2019-02-11 19:24
I'm going to close this out as I've settled on ESLint and Prettier as a baseline in #1152. There's plenty of exclusions I've added here to ensure the initial PR wasn't disruptive at all to the previous style, but if someone wants to improve things that's the place to go:

https://github.com/up-for-grabs/up-for-grabs.net/blob/fb5c13f27385a424164f0c4860a3ccba01bede9c/.eslintrc.json

Having pre-commit hooks is a low-priority for me (CI will catch any regressions now) but there are plenty of guides out there if someone wants to get this working locally, e.g. https://medium.com/@rashtay/how-to-run-eslint-using-pre-commit-hook-25984fbce17e

**Closed as completed by shiftkey** 2019-02-11 19:24 UTC
Labels: up-for-grabs
